### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by GewoonYorick**

### CODE REVIEW

**Comment by nolsen42** [comment]
Uh, what again?

**Comment by AWSCUBER** [comment]
hi dear team
i have a problem with my znc bot manager : 
it work verry well but with wrong password request : 

[14:53] <HeLiCops> !request HeLiCops
[14:53] <@ReQZnC> HeLiCops: Creating your new account, details will be sent in private shortly.
--------------------------------------------------------
[14:54] <ReQZnC> Account created!
[14:54] <ReQZnC> Username: HeLiCops
[14:54] <ReQZnC> Password: i0iqU9h5Fl
[14:54] <ReQZnC> (It is *highly* recommended to change this generated password, later on.)
[14:54] <ReQZnC> Webpanel: weedbox.net:9090
[14:54] <ReQZnC> Note: While your account is created, you cannot connect to any IRC network until an admin approves your account!
[14:54] <ReQZnC> Once approved, you'll be able to connect to any IRC network, approvals are usually quick, but if not, ping an admin!
[14:54] <ReQZnC> You can find our ToS at weedbox.net:9090
----------------------------------------------------------
/s -m weedbox.net:9090 HeLiCops:i0iqU9h5Fl
----------------------------------------------------------
[16:38] *** Connecting to weedbox.net (9090)
-
Invalid Password
-
[16:38] *** Disconnected

**Comment by nolsen42** [comment]
Did you just post your password on this closed pull request...

**Comment by AWSCUBER** [comment]
now it work verry well 

 

[14:32] <@LoGiQue> !restart
[14:32] <@AccounT> Restarting...
[14:32] <@AccounT> Restart completed!
[14:33] <PubLiQue> !request
[14:33] <@AccounT> PubLiQue: Syntax: !request username
[14:33] <PubLiQue> !request PubLiQue
[14:33] <@AccounT> PubLiQue: Creating your new account, details will be sent in private shortly.


[14:33] *** Joins: PubLiQue- (~cloneuser@gprs1.telecom.ronsor.pw)

 

it connect automaticly 

 

but i wanna know :

 

i start the znc bot with : ./bot config.json

and  when i close the console shell the bot stop working ...

 

tel me pls how tel the bot working even if i close the sonsole shell 

thinx

**Pull request closed without merging**
